### ISSUE TITLE
Шрифты не соответствуют макету.

### ISSUE THREAD

**Issue by tardiva** [StasRomanov/project1#1]
https://github.com/StasRomanov/project1/blob/80ba40d11adcea20a2c3ca26c9947a24115962c7/style.css#L2

почему здесь fontsed? в макете используются Exo2.0-Thin (который к этому макету приложен) + в других местах Trebuchet MS

<img width="1081" alt="prototype_sketch_fonts" src="https://user-images.githubusercontent.com/20556229/55353547-40478000-54cc-11e9-904d-fca7f484f834.png">

**Comment by StasRomanov** [comment]
fixed
