### ISSUE TITLE
Оптимизировать отступы.

### ISSUE THREAD

**Issue by tardiva** [StasRomanov/project1#3]
1. Обычно если у текста есть отступ с одной стороны то подразумевается что и с другой такой же тоже есть

2. Мне кажется что проще добавить контейнер (div), задать ему отступы сверху, слева и справа. а уже в него засунуть все заголовки и тексты. это позволит не повторять боковые отступы каждый раз 
<img width="462" alt="margins paddings" src="https://user-images.githubusercontent.com/20556229/55354959-a8e42c00-54cf-11e9-977e-3fb161372402.png">
(см скриншот)

**Comment by StasRomanov** [comment]
fixed
