### ISSUE TITLE
Убрать отрицательные margins

### ISSUE THREAD

**Issue by tardiva** [StasRomanov/project1#4]
https://github.com/StasRomanov/project1/blob/80ba40d11adcea20a2c3ca26c9947a24115962c7/style.css#L30

а зачем тут отрицательный margin? их стараются использовать в крайних случаях только. ты боролся со стилями добавленными браузером? погугли про сброс стилей. либо просто добавляешь margin-top: 0; margin-bottom: сколько-там-нужно;
 
когда блоки текста идут вот так друг за другом им обычно делают только нижний margin. тогда если понадобится убрать один - ничего особенно не сломается во внешнем виде.

**Comment by StasRomanov** [comment]
fixed
