### ISSUE TITLE
Кот должен быть фоном

### ISSUE THREAD

**Issue by tardiva** [StasRomanov/project1#5]
Нужно сделать кота-фон так, чтобы при изменении количества текста он (кот) никуда не съезжал. 

Либо 1 - делать карточку неизменного размера так что если текста совсем много он может быть поверх кота. либо 2 - чтобы карточка увеличивалась в размерах а расстояние между котом и текстом сохранялось

мне больше нравится первый, это же скорее фон а не картинка.
<img width="417" alt="background_issue" src="https://user-images.githubusercontent.com/20556229/55356178-ded6df80-54d2-11e9-853f-c8532e9fd7f9.png">

**Comment by StasRomanov** [comment]
fixed
