### ISSUE TITLE
Убрать ненужный margin

### ISSUE THREAD

**Issue by tardiva** [StasRomanov/project1#7]
https://github.com/StasRomanov/project1/blob/80ba40d11adcea20a2c3ca26c9947a24115962c7/style.css#L154

нужно как-то избавиться от этой грязищи. попробуй поменять `align-items` для allContent. сделай `flex-start`. и для всех eat'ов вместо `margin: auto;` сделать `margin: 0 auto;`вроде так нормально получается.

**Comment by StasRomanov** [comment]
fixed
